Team Value PRs
sandeepmehta2155/finalrepo pull request #1
Opened 2021-05-04 18:17 UTC by sandeepmehta2155

2021-05-04 18:26 UTC, kajol-rep reviewed
Good work Sandeep ! 
I would like to suggest few things to improve your design:

1.  In home page a picture is missing from featured series.
2. In home page you can keep the chatbot component at the bottom.
3. In products page you can increase the width of the card and let there be some space around the image so that it will look good.
4. In wishlist page  please have a look at heart icon it flowing outside the border.
5. In cart page remove from cart button is flowing out of the box.
6. Give some color hover effects to the buttons. So it will look like a button.

2021-05-04 20:24 UTC, sandeepmehta2155 commented
> Good work Sandeep !
> I would like to suggest few things to improve your design:
> 
> 1. In home page a picture is missing from featured series.
> 2. In home page you can keep the chatbot component at the bottom.
> 3. In products page you can increase the width of the card and let there be some space around the image so that it will look good.
> 4. In wishlist page  please have a look at heart icon it flowing outside the border.
> 5. In cart page remove from cart button is flowing out of the box.
> 6. Give some color hover effects to the buttons. So it will look like a button.

1. Image is now working
2. Removed Chat Bot as it is of no use
3. Card width is increased and I wanted image to occupy 100% of card width
4. Issue rectified
5. Issue rectified
6. Hover effect added

2021-05-05 05:53 UTC, hntejas requested changes
Hi Sandeep, here are some of my functional/UI suggestions

1) The site is not responsive at desktop resolutions
2) Product filter is below the footer and can be moved to a right place 
3) Add to cart button is difficult to access on the products 
4) The header is not responsive in mobile resolution 
5) If the user is already logged in/ the login page can have the logout option 
6) It is recommended to have  cursor as point on action buttons only

2021-05-06 18:14 UTC, sandeepmehta2155 commented
> Hi Sandeep, here are some of my functional/UI suggestions
> 
> 1. The site is not responsive at desktop resolutions
> 2. Product filter is below the footer and can be moved to a right place
> 3. Add to cart button is difficult to access on the products
> 4. The header is not responsive in mobile resolution
> 5. If the user is already logged in/ the login page can have the logout option
> 6. It is recommended to have  cursor as point on action buttons only

1. Made responsive
2. Filter moved to product page
3. Issue resolved
4. Made Responsive
5. Need to work on persistence
6. Wrongly inherited due to component library

2021-05-07 04:19 UTC, hntejas commented
> > Hi Sandeep, here are some of my functional/UI suggestions
> > 
> > 1. The site is not responsive at desktop resolutions
> > 2. Product filter is below the footer and can be moved to a right place
> > 3. Add to cart button is difficult to access on the products
> > 4. The header is not responsive in mobile resolution
> > 5. If the user is already logged in/ the login page can have the logout option
> > 6. It is recommended to have  cursor as point on action buttons only
> 
> 1. Made responsive
> 2. Filter moved to product page
> 3. Issue resolved
> 4. Made Responsive
> 5. Need to work on persistence
> 6. Wrongly inherited due to component library

Hi Sandeep, Thanks for making the fixes. 

here are few of the issues that I observed.
1) The cart line is overflowing into the Cart summary
2) The Product filter is now not visible 
3) Sorting and filter buttons in the mobile resolution does not respond to click 
4) Some images in home page are not loading 
5) The cursor is still pointer in all pages

2021-05-07 06:19 UTC, sandeepmehta2155 commented
> > > Hi Sandeep, here are some of my functional/UI suggestions
> > > 
> > > 1. The site is not responsive at desktop resolutions
> > > 2. Product filter is below the footer and can be moved to a right place
> > > 3. Add to cart button is difficult to access on the products
> > > 4. The header is not responsive in mobile resolution
> > > 5. If the user is already logged in/ the login page can have the logout option
> > > 6. It is recommended to have  cursor as point on action buttons only
> > 
> > 
> > 
> > 1. Made responsive
> > 2. Filter moved to product page
> > 3. Issue resolved
> > 4. Made Responsive
> > 5. Need to work on persistence
> > 6. Wrongly inherited due to component library
> 
> Hi Sandeep, Thanks for making the fixes.
> 
> here are few of the issues that I observed.
> 
> 1. The cart line is overflowing into the Cart summary
> 2. The Product filter is now not visible
> 3. Sorting and filter buttons in the mobile resolution does not respond to click
> 4. Some images in home page are not loading
> 5. The cursor is still pointer in all pages

There was mild issue in deployment, changes have been updated

2021-05-07 08:08 UTC, kajol-rep approved these changes
I have reviewed your changes. You are GTG ahead.

2021-05-08 12:17 UTC, hntejas reviewed
Hi Sandeep, 

Here are some of my suggestions regarding clean code and code structuring practices. These are only for code organization and code readability and will not affect performance of the application

1) Components and Pages can be broken down and organized into different folders, the same with context and it's related utilities
2) For the naming conventions :
  a) components and it's files can be PascalCase
  b) variables and functions can be camelCase
  c) style related naming can be kebab-case
3) The file extensions can be maintained consistent as jsx or js.

2021-05-08 12:17 UTC, hntejas commented on src/Products-Page/product-display-page.js
> +  return <div></div>;
unused components can be cleaned up

2021-05-08 13:01 UTC, sandeepmehta2155 commented on src/Products-Page/product-display-page.js
> +  return <div></div>;
Used components removed

2021-05-08 13:03 UTC, sandeepmehta2155 commented on src/Cart-Page/cart.js
> +  const { itemsInProduct, productDispatch } = useProd();
As I had one day to change the whole UI I wasn't aware of this thanks for pointing out. Awaiting for further review if any changes are to be made.

2021-05-08 13:49 UTC, hntejas commented
> > Hi Sandeep,
> > Here are some of my suggestions regarding clean code and code structuring practices. These are only for code organization and code readability and will not affect performance of the application
> > 
> > 1. Components and Pages can be broken down and organized into different folders, the same with context and it's related utilities
> > 2. For the naming conventions :
> >    a) components and it's files can be PascalCase
> >    b) variables and functions can be camelCase
> >    c) style related naming can be kebab-case
> > 3. The file extensions can be maintained consistent as jsx or js.
> 
> I will surely implement in further projects. Thanks again, awaiting for further reviews.

Hi Sandeep, looks good in that case from my end.

2021-05-08 13:50 UTC, hntejas approved these changes

2021-05-10 12:51 UTC, merged